/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project1;

import java.security.MessageDigest;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author tharm
 */
public class ChangePassword extends javax.swing.JFrame {
    Connection conn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    
    
    
    /**
     * Creates new form ChangePassword
     */
    public ChangePassword() {
        initComponents();
        lbl_username.setVisible(false);
    }
    
    public ChangePassword (String para)
    {
       initComponents();
       
       lbl_username.setText(para);
       lbl_username.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_newpassword = new javax.swing.JLabel();
        lbl_confirmpassword = new javax.swing.JLabel();
        txt_submit = new javax.swing.JButton();
        txt_confirmpassword = new javax.swing.JPasswordField();
        cb_showpassword = new javax.swing.JCheckBox();
        txt_newpassword = new javax.swing.JPasswordField();
        lbl_username = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_newpassword.setText("New Password");
        lbl_newpassword.setName(""); // NOI18N

        lbl_confirmpassword.setText("Confirm Password");
        lbl_confirmpassword.setName("lbl_confirmpassword"); // NOI18N

        txt_submit.setText("Submit");
        txt_submit.setName("btn_login"); // NOI18N
        txt_submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_submitActionPerformed(evt);
            }
        });

        txt_confirmpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_confirmpasswordActionPerformed(evt);
            }
        });

        cb_showpassword.setText("Show Password");
        cb_showpassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cb_showpasswordMouseClicked(evt);
            }
        });

        lbl_username.setText("Username");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbl_username)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_submit))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_newpassword)
                            .addComponent(lbl_confirmpassword))
                        .addGap(56, 56, 56)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_confirmpassword, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                            .addComponent(txt_newpassword))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(cb_showpassword)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_newpassword)
                    .addComponent(cb_showpassword)
                    .addComponent(txt_newpassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_confirmpassword)
                    .addComponent(txt_confirmpassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_submit)
                    .addComponent(lbl_username))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton1.setText("Exit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_submitActionPerformed
       if(txt_newpassword.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "New Password field is empty");
        }
        if(txt_confirmpassword.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Confirm Password field is empty");
        }
        
        else if(txt_newpassword.getText().equals(txt_confirmpassword.getText()))
        {
            try
            {
                Pattern sPattern = Pattern.compile("[a-zA-Z0-9]*");
                Matcher sMatcher = sPattern.matcher(txt_newpassword.getText());
                if(txt_newpassword.getText().length()>=8 && !sMatcher.matches())
                {
                    try
                    {
                        conn = Phpmyadmin.ConnectDB();
                        String check="UPDATE login SET password='"+md5(txt_newpassword.getText().toCharArray())+"' WHERE username='"+lbl_username.getText()+"'";
                        try
                        {
                            pst = conn.prepareStatement(check);
                            pst.executeUpdate();
                            JOptionPane.showMessageDialog (null, "Password changed successfully", "Success", JOptionPane.INFORMATION_MESSAGE);
                            new Login().setVisible(true);
                            this.dispose();
                        }
                        catch(Exception e)
                        {
                            JOptionPane.showMessageDialog (null, "Password cant be changed", "Error", JOptionPane.WARNING_MESSAGE);
                        }
                    }
                    catch(Exception e)
                    {

                    }
                }
                else
                {
                   JOptionPane.showMessageDialog(null, "Password lenght should be more than 8 characters with Upper case, lower case, number and symbols");
                }
            }
            catch(Exception e)
            {

            }   
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Password is not matched", "Not matched", JOptionPane.INFORMATION_MESSAGE);
            txt_confirmpassword.setText("");
        }
    }//GEN-LAST:event_txt_submitActionPerformed

    private void txt_confirmpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_confirmpasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_confirmpasswordActionPerformed

    private void cb_showpasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cb_showpasswordMouseClicked
        if(cb_showpassword.isSelected())
        {
            txt_newpassword.setEchoChar((char)0);
        }
        else
        {
            txt_newpassword.setEchoChar('*');
        }
    }//GEN-LAST:event_cb_showpasswordMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed
    private String md5(char[] c)
    {
        try
        {
            MessageDigest md = MessageDigest.getInstance("MD5");
            md.update((new String(c)).getBytes());
            String str = new String (md.digest());
            return str;
        }
        catch(Exception e)
        {
            
        }
        return "";
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChangePassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox cb_showpassword;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_confirmpassword;
    private javax.swing.JLabel lbl_newpassword;
    private javax.swing.JLabel lbl_username;
    private javax.swing.JPasswordField txt_confirmpassword;
    private javax.swing.JPasswordField txt_newpassword;
    private javax.swing.JButton txt_submit;
    // End of variables declaration//GEN-END:variables
}
